{"uuid": "c8358541-d9b0-4aca-895b-16e86d649fdf", "children": ["b070c273-8642-4e09-a611-55a92cf344c3", "ea97984f-4764-45e7-ab94-9d5492cc1759", "bb4a567a-b086-4f46-bf46-ea078174d940", "3bf36940-3e2a-4c68-9c5d-dffb7bbbca6e", "04a744b8-5ab5-40a8-a599-427e27e97bcc", "d0909fe7-9a89-42d3-bdd3-3fd934157fef", "be1cfa8a-a2df-4354-9f54-655107aa458f", "0a275047-c080-4697-80ba-c3729507e5e0"], "befores": [{"name": "setup", "status": "passed", "start": 1658483367686, "stop": 1658483386653}], "afters": [{"name": "setup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Unable to find session with requested ID: 61a4113c-8c98-4887-9ba3-5e0290fd46e8. The session might have been closed if no request came in 90000ms or never existed\nBuild info: version: 'unknown', revision: 'unknown', time: 'unknown'\nSystem info: host: 'rdc-manual-648dc5799d-hqjgv', ip: '240.1.17.85', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.188+', java.version: '11.0.15'\nDriver info: driver.version: unknown\n\n", "trace": "  File \"C:\\Users\\Chetan_B\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\Chetan_B\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Chetan_B\\PycharmProjects\\SollisAutomationFramework\\tests_Sollis_MVP\\conftest.py\", line 30, in setup\n    driver.quit()\n  File \"C:\\Users\\Chetan_B\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 698, in quit\n    self.execute(Command.QUIT)\n  File \"C:\\Users\\Chetan_B\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Chetan_B\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1658483542220, "stop": 1658483542502}], "start": 1658483367686, "stop": 1658483542502}