{"uuid": "173e159c-dd49-4a60-9e14-35260b79c38a", "children": ["731a83f4-8acf-435f-af4c-b3d17f37bfbf", "529d3de6-b1ca-4cd3-a2b1-90e020d0f957", "5fe4b5a4-c203-4b18-8255-bda9e7a5cd70", "7615a8fb-7c00-4468-84bd-67d5c4028be7", "94c9ce1f-b7b0-4c6f-8d2a-23b75efd8d25", "dfe67093-5a89-484f-af41-a9cfa18c7868", "e02f67b5-bfcc-4f02-88b7-b18f9ca4528b"], "befores": [{"name": "setup", "status": "passed", "start": 1658483542554, "stop": 1658483570666}], "afters": [{"name": "setup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Unable to find session with requested ID: 04ded100-2089-4c49-bfc3-8461897470f6. The session might have been closed if no request came in 90000ms or never existed\nBuild info: version: 'unknown', revision: 'unknown', time: 'unknown'\nSystem info: host: 'rdc-manual-648dc5799d-d8v9c', ip: '240.1.30.240', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.188+', java.version: '11.0.15'\nDriver info: driver.version: unknown\n\n", "trace": "  File \"C:\\Users\\Chetan_B\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\Chetan_B\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Chetan_B\\PycharmProjects\\SollisAutomationFramework\\tests_Sollis_MVP\\conftest.py\", line 30, in setup\n    driver.quit()\n  File \"C:\\Users\\Chetan_B\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 698, in quit\n    self.execute(Command.QUIT)\n  File \"C:\\Users\\Chetan_B\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Chetan_B\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1658483720992, "stop": 1658483721292}], "start": 1658483542554, "stop": 1658483721292}