{"uuid": "9331d03f-389a-4505-bcd4-e87e4cbd3a41", "children": ["e3a4610d-c050-4560-b5d1-35b878559488", "d2ee247a-a1c0-4abc-8e55-c1b6558a3fd7", "23b8e73e-b12e-43d0-9c9d-e065027c4778", "432589dc-f67d-4d9f-8324-97587004c444", "77418b56-2122-42e4-a488-aecc35d0749e", "08c7a189-1aeb-4da6-b2ef-dd746d16703c", "4ed465ef-97a3-46f6-b45b-0c1e38d59c23"], "befores": [{"name": "setup", "status": "passed", "start": 1658484013839, "stop": 1658484037641}], "afters": [{"name": "setup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Unable to find session with requested ID: 20ed50d8-33f5-4bdc-b2e1-993691049fb9. The session might have been closed if no request came in 90000ms or never existed\nBuild info: version: 'unknown', revision: 'unknown', time: 'unknown'\nSystem info: host: 'rdc-manual-648dc5799d-hqjgv', ip: '240.1.17.85', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.188+', java.version: '11.0.15'\nDriver info: driver.version: unknown\n\n", "trace": "  File \"C:\\Users\\Chetan_B\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\Chetan_B\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Chetan_B\\PycharmProjects\\SollisAutomationFramework\\tests_Sollis_MVP\\conftest.py\", line 30, in setup\n    driver.quit()\n  File \"C:\\Users\\Chetan_B\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 698, in quit\n    self.execute(Command.QUIT)\n  File \"C:\\Users\\Chetan_B\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Chetan_B\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1658484207774, "stop": 1658484208164}], "start": 1658484013839, "stop": 1658484208164}